CREATE DATABASE [$(DB_NAME)]
GO
USE [$(DB_NAME)]
GO

CREATE SCHEMA [File]
GO
CREATE SCHEMA [Person]
GO
CREATE SCHEMA [Business]
GO
CREATE SCHEMA [Offer]
GO
CREATE SCHEMA [Pending]
GO
CREATE SCHEMA [Communication]
GO
CREATE SCHEMA [Animal]
GO
CREATE SCHEMA [Product]
GO
CREATE SCHEMA [Service]
GO

CREATE TABLE [File].[Album](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	Capacity TINYINT NOT NULL,
	Reserved TINYINT NOT NULL,
);
GO	
	
CREATE TABLE [File].[Image](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	AlbumID UNIQUEIDENTIFIER NOT NULL,
	Width INT NOT NULL,
	Height INT NOT NULL,
	ImageData VARBINARY(MAX) NOT NULL,



	CONSTRAINT FK_Image_Album FOREIGN KEY (AlbumID) REFERENCES [File].[Album](ID) ON DELETE CASCADE
);
GO
	
CREATE TABLE [Person].[Account](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	Contact VARCHAR(255) NOT NULL,
	PasswordHash VARCHAR(44) NOT NULL,
	PasswordSalt VARCHAR(24) NOT NULL,
	AccessLevel TINYINT NOT NULL,
	Verified BIT
);
GO

CREATE TABLE [Person].[User](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	AccountID UNIQUEIDENTIFIER NOT NULL,
	UserName NVARCHAR(50) NOT NULL,
	ProfilePictureID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [File].[Album](ID),

	CONSTRAINT FK_User_Account FOREIGN KEY (AccountID) REFERENCES [Person].[Account](ID) ON DELETE CASCADE
);
GO

CREATE TABLE [Business].[Franchise](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	OwnerID UNIQUEIDENTIFIER NOT NULL,
	FranchiseName NVARCHAR(50) NOT NULL,
	LogoID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [File].[Album](ID),

	CONSTRAINT FK_Franchise_User FOREIGN KEY (OwnerID) REFERENCES [Person].[User](ID) ON DELETE CASCADE
);
GO

CREATE TABLE [Business].[Facility](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	FranchiseID UNIQUEIDENTIFIER NOT NULL,
	City NVARCHAR(100) NOT NULL,
	Street NVARCHAR(150) NOT NULL,
	Contact VARCHAR(255),

	CONSTRAINT FK_Facility_Franchise FOREIGN KEY (FranchiseID) REFERENCES [Business].[Franchise](ID) ON DELETE CASCADE
);
GO

CREATE TABLE [Offer].[Listing](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	ListingName NVARCHAR(50) NOT NULL,
	ListingDescription NVARCHAR(500) NOT NULL,
	AlbumID UNIQUEIDENTIFIER,

	CONSTRAINT FK_Listing_Album FOREIGN KEY (AlbumID) REFERENCES [File].[Album](ID)
);
GO

CREATE TABLE [Communication].[Thread](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	Title NVARCHAR(100) NOT NULL,
	Contents NVARCHAR(1000) NOT NULL,
	PosterID UNIQUEIDENTIFIER NOT NULL,
	Creation DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	Edited BIT  NOT NULL,
	ListingID UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT FK_Thread_Listing FOREIGN KEY (ListingID) REFERENCES [Offer].[Listing](ID) ON DELETE CASCADE,
	CONSTRAINT FK_Thread_User FOREIGN KEY (PosterID) REFERENCES [Person].[User](ID) ON DELETE CASCADE
);
GO

CREATE TABLE [Communication].[Comment](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	Contents NVARCHAR(1000) NOT NULL,
	PosterID UNIQUEIDENTIFIER,
	Creation DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	Edited BIT  NOT NULL,
	ThreadID UNIQUEIDENTIFIER NOT NULL,
	ParentCommentID UNIQUEIDENTIFIER,

	CONSTRAINT FK_Comment_Thread FOREIGN KEY (ThreadID) REFERENCES [Communication].[Thread](ID) ON DELETE CASCADE,
	CONSTRAINT FK_Comment_Comment FOREIGN KEY (ParentCommentID) REFERENCES [Communication].[Comment](ID),
	CONSTRAINT FK_Comment_User FOREIGN KEY (PosterID) REFERENCES [Person].[User](ID) 
);
GO

CREATE TABLE [Pending].[Registration](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	AccountID UNIQUEIDENTIFIER NOT NULL,
	Code INT NOT NULL,
	Expiry DATETIME2 NOT NULL,
	NextAttempt DATETIME2 NOT NULL,

	CONSTRAINT FK_Registration_Account FOREIGN KEY (AccountID) REFERENCES [Person].[Account](ID) ON DELETE CASCADE
);
GO

CREATE TABLE [Animal].[Kind](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	Title NVARCHAR(30) NOT NULL,
	AlbumID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [File].[Album](ID) NOT NULL
);
GO

CREATE TABLE [Animal].[Breed](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	KindID UNIQUEIDENTIFIER NOT NULL,	
	Title NVARCHAR(30) NOT NULL,
	Scale TINYINT NOT NULL,
	Diet TINYINT NOT NULL,
	Investment REAL NOT NULL,
	Territory REAL NOT NULL,
	Pricing REAL NOT NULL,
	Longevity REAL NOT NULL,
	Cohabitation REAL NOT NULL,
	AlbumID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [File].[Album](ID) NOT NULL,
	
	CONSTRAINT FK_Breed_Kind FOREIGN KEY (KindID) REFERENCES [Animal].[Kind](ID) ON DELETE CASCADE
);
GO

CREATE TABLE [Animal].[Individual](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	BreedID UNIQUEIDENTIFIER NOT NULL,
	AnimalName NVARCHAR(30) NOT NULL,
	BirthDate DATETIME2 NOT NULL,
	AlbumID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [File].[Album](ID) NOT NULL,
	Sex BIT NOT NULL,

	CONSTRAINT FK_Animal_Breed FOREIGN KEY (BreedID) REFERENCES [Animal].[Breed](ID) ON DELETE CASCADE
);
GO

CREATE TABLE [Service].[MedicalProcedure](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	ProcedureDescription NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE [Service].[MedicalProcedureSpecification](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	ProcedureID UNIQUEIDENTIFIER NOT NULL,
	KindID UNIQUEIDENTIFIER NOT NULL,
	BreedID UNIQUEIDENTIFIER,
	ApproximateAgeDays INT,
	SexSpecific BIT,
	Optional BIT NOT NULL,

	CONSTRAINT FK_MedProcedureSpecification_Procedure FOREIGN KEY (ProcedureID) REFERENCES [Service].[MedicalProcedure](ID) ON DELETE CASCADE,
	CONSTRAINT FK_MedProcedureSpecification_Kind FOREIGN KEY (KindID) REFERENCES [Animal].[Kind](ID) ON DELETE CASCADE,
	CONSTRAINT FK_MedProcedureSpecification_Breed FOREIGN KEY (BreedID) REFERENCES [Animal].[Breed](ID)
);
GO

CREATE TABLE [Animal].[MedicalRecordEntry](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	ProcedureID UNIQUEIDENTIFIER NOT NULL,
	AnimalID UNIQUEIDENTIFIER NOT NULL,
	Notes NVARCHAR(100) NOT NULL,
	DatePerformed DATETIME2 NOT NULL,

	CONSTRAINT FK_MedicalRecordEntry_Procedure FOREIGN KEY (ProcedureID) REFERENCES [Service].[MedicalProcedure](ID) ON DELETE CASCADE,
	CONSTRAINT FK_MedicalRecordEntry_Animal FOREIGN KEY(AnimalID) REFERENCES [Animal].[Individual](ID) ON DELETE CASCADE
);
GO

USE master 
GO                                                                            

