CREATE DATABASE [$(DB_NAME)]
GO
USE [$(DB_NAME)]
GO

CREATE SCHEMA [File]
GO
CREATE SCHEMA [Person]
GO
CREATE SCHEMA [Business]
GO
CREATE SCHEMA [Offer]
GO
CREATE SCHEMA [Pending]
GO
CREATE SCHEMA [Communication]
GO

CREATE TABLE [File].[Album](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	Capacity TINYINT NOT NULL,
	Reserved TINYINT NOT NULL,
);
GO	
	
CREATE TABLE [File].[Image](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	AlbumID UNIQUEIDENTIFIER NOT NULL,
	Width INT NOT NULL,
	Height INT NOT NULL,
	ImageData VARBINARY(MAX) NOT NULL,



	CONSTRAINT FK_Image_Album FOREIGN KEY (AlbumID) REFERENCES [File].[Album](ID) ON DELETE CASCADE
);
GO
	
CREATE TABLE [Person].[Account](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	Contact VARCHAR(255) NOT NULL,
	PasswordHash VARCHAR(44) NOT NULL,
	PasswordSalt VARCHAR(24) NOT NULL,
	AccessLevel TINYINT NOT NULL,
	Verified BIT
);
GO

CREATE TABLE [Person].[User](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	AccountID UNIQUEIDENTIFIER NOT NULL,
	UserName NVARCHAR(50) NOT NULL,
	ProfilePictureID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [File].[Album](ID),

	CONSTRAINT FK_User_Account FOREIGN KEY (AccountID) REFERENCES [Person].[Account](ID) ON DELETE CASCADE
);
GO

CREATE TABLE [Business].[Franchise](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	OwnerID UNIQUEIDENTIFIER NOT NULL,
	FranchiseName NVARCHAR(50) NOT NULL,
	LogoID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [File].[Album](ID),

	CONSTRAINT FK_Franchise_User FOREIGN KEY (OwnerID) REFERENCES [Person].[User](ID) ON DELETE CASCADE
);
GO

CREATE TABLE [Business].[Facility](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	FranchiseID UNIQUEIDENTIFIER NOT NULL,
	City NVARCHAR(100) NOT NULL,
	Street NVARCHAR(150) NOT NULL,
	Contact VARCHAR(255),

	CONSTRAINT FK_Facility_Franchise FOREIGN KEY (FranchiseID) REFERENCES [Business].[Franchise](ID) ON DELETE CASCADE
);
GO

CREATE TABLE [Offer].[Listing](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	ListingName NVARCHAR(50) NOT NULL,
	ListingDescription NVARCHAR(500) NOT NULL,
	AlbumID UNIQUEIDENTIFIER,

	CONSTRAINT FK_Listing_Album FOREIGN KEY (AlbumID) REFERENCES [File].[Album](ID)
);
GO

CREATE TABLE [Communication].[Thread](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	Title NVARCHAR(100) NOT NULL,
	Contents NVARCHAR(1000) NOT NULL,
	PosterID UNIQUEIDENTIFIER NOT NULL,
	Creation DATETIME2 NOT NULL,
	Edited BIT  NOT NULL,
	ListingID UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT FK_Thread_Listing FOREIGN KEY (ListingID) REFERENCES [Offer].[Listing](ID) ON DELETE CASCADE,
	CONSTRAINT FK_Thread_User FOREIGN KEY (PosterID) REFERENCES [Person].[User](ID) ON DELETE CASCADE
);

CREATE TABLE [Communication].[Comment](
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	Contents NVARCHAR(1000) NOT NULL,
	PosterID UNIQUEIDENTIFIER,
	Creation DATETIME2 NOT NULL,
	Edited BIT  NOT NULL,
	ThreadID UNIQUEIDENTIFIER NOT NULL,
	ParentCommentID UNIQUEIDENTIFIER,

	CONSTRAINT FK_Comment_Thread FOREIGN KEY (ThreadID) REFERENCES [Communication].[Thread](ID) ON DELETE CASCADE,
	CONSTRAINT FK_Comment_Comment FOREIGN KEY (ParentCommentID) REFERENCES [Communication].[Comment](ID),
	CONSTRAINT FK_Comment_User FOREIGN KEY (PosterID) REFERENCES [Person].[User](ID) 
);


CREATE TABLE [Pending].[Registration](
	AccountID UNIQUEIDENTIFIER PRIMARY KEY,
	Code INT NOT NULL,
	Expiry DATETIME2 NOT NULL,
	NextAttempt DATETIME2 NOT NULL,

	CONSTRAINT FK_Registration_Account FOREIGN KEY (AccountID) REFERENCES [Person].[Account](ID) ON DELETE CASCADE
);
GO

USE master 
GO                                                                            

